language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - pip install scipy
  - pip install numpy
# command to install dependencies
install:
  - pip install .

# command to run tests
script: 
  - "python ./upkeep/qtim_test_master.py"