language: python
python:
  - "2.7"
before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
# command to install dependencies
install:
  - pip install --user travis-sphinx
  - export PATH=$HOME/.local/bin:$PATH
  - pip install .

notifications:
  slack: qtim:jp1UTPVP5wscM2R6eyFHJIb4

# command to run tests
script: 
  - "python ./tests/initial_test.py"
  - travis-sphinx build --source=sphinx build
    
after_success:
  - travis-sphinx deploy